#priority 7000
#reloadable
import crafttweaker.item.IItemStack;
import crafttweaker.liquid.ILiquidStack;
import crafttweaker.event.PlayerPickupItemEvent;
import mods.jei.JEI;

var banned_items = [
    //pickaxe
    <item:minecraft:iron_pickaxe>,
    <item:minecraft:diamond_pickaxe>,
    <item:minecraft:golden_pickaxe>,
    <item:abyssalcraft:apick>,
    <item:abyssalcraft:corpick>,
    <item:abyssalcraft:dreadiumpickaxe>,
    <item:abyssalcraft:ethaxiumpickaxe>,
    <item:scp:sturdy_pickaxe>,
    <item:scp:telekill_pickaxe>,
    <item:sakura:sakura_pickaxe>,
    <item:forestry:bronze_pickaxe>,
    <item:enderio:item_dark_steel_pickaxe>,
    <item:enderio:item_dark_steel_pickaxe>.withTag({"enderio.darksteel.upgrade.travel": {level: 0}, "enderio.darksteel.upgrade.direct": {level: 0}, "enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}, "enderio.darksteel.upgrade.spoon": {level: 0}, "enderio.darksteel.upgrade.tnt": {level: 0}}),
    <item:enderio:item_dark_steel_pickaxe>.withTag({"enderio.darksteel.upgrade.travel": {level: 0}, "enderio.darksteel.upgrade.direct": {level: 0}, "enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}, "enderio.darksteel.upgrade.spoon": {level: 0}, "enderio.darksteel.upgrade.depth": {level: 0}, "enderio.darksteel.upgrade.carpet": {level: 0}, "enderio.darksteel.upgrade.tnt": {level: 4}}),
    <item:galacticraftcore:steel_pickaxe>,
    <item:galacticraftplanets:desh_pick>,
    <item:galacticraftplanets:desh_pick_slime>,
    <item:galacticraftplanets:titanium_pickaxe>,
    <item:galacticraftplanets:volcanic_pickaxe>,
    <item:avaritia:infinity_pickaxe>.withTag({ench: [{lvl: 10 as short, id: 35 as short}]}),
    //axe
    <item:minecraft:iron_axe>,
    <item:minecraft:diamond_axe>,
    <item:minecraft:golden_axe>,
    <item:abyssalcraft:aaxe>,
    <item:abyssalcraft:coraxe>,
    <item:abyssalcraft:dreadiumaxe>,
    <item:abyssalcraft:ethaxiumaxe>,
    <item:scp:sturdy_axe>,
    <item:scp:telekill_axe>,
    <item:sakura:sakura_axe>,
    <item:enderio:item_dark_steel_axe>,
    <item:enderio:item_dark_steel_axe>.withTag({"enderio.darksteel.upgrade.hoe": {level: 0}, "enderio.darksteel.upgrade.direct": {level: 0}, "enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}}),
    <item:galacticraftcore:steel_axe>,
    <item:galacticraftplanets:desh_axe>,
    <item:galacticraftplanets:titanium_axe>,
    <item:avaritia:infinity_axe>,
    //sword
    <item:minecraft:iron_sword>,
    <item:minecraft:diamond_sword>,
    <item:minecraft:golden_sword>,
    <item:abyssalcraft:asword>,
    <item:abyssalcraft:corsword>,
    <item:abyssalcraft:dreadiumsword>,
    <item:abyssalcraft:ethaxiumsword>,
    <item:scp:sturdy_sword>,
    <item:scp:telekill_sword>,
    <item:enderio:item_dark_steel_sword>,
    <item:enderio:item_dark_steel_sword>.withTag({"enderio.darksteel.upgrade.travel": {level: 0}, "enderio.darksteel.upgrade.direct": {level: 0}, "enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}}),
    <item:galacticraftcore:steel_sword>,
    <item:galacticraftplanets:desh_sword>,
    <item:galacticraftplanets:titanium_sword>,
    <item:avaritia:skullfire_sword>,
    <item:avaritia:infinity_sword>,
    //hoe
    <item:minecraft:iron_hoe>,
    <item:minecraft:diamond_hoe>,
    <item:minecraft:golden_hoe>,
    <item:abyssalcraft:ahoe>,
    <item:abyssalcraft:corhoe>,
    <item:abyssalcraft:dreadiumhoe>,
    <item:abyssalcraft:ethaxiumhoe>,
    <item:scp:sturdy_hoe>,
    <item:scp:telekill_hoe>,
    <item:sakura:sakura_hoe>,
    <item:galacticraftcore:steel_hoe>,
    <item:galacticraftplanets:desh_hoe>,
    <item:galacticraftplanets:titanium_hoe>,
    <item:avaritia:infinity_hoe>,
    //shovel
    <item:minecraft:iron_shovel>,
    <item:minecraft:diamond_shovel>,
    <item:minecraft:golden_shovel>,
    <item:abyssalcraft:ashovel>,
    <item:abyssalcraft:corshovel>,
    <item:abyssalcraft:dreadiumshovel>,
    <item:abyssalcraft:ethaxiumshovel>,
    <item:scp:sturdy_shovel>,
    <item:scp:telekill_shovel>,
    <item:sakura:sakura_shovel>,
    <item:forestry:bronze_shovel>,
    <item:galacticraftcore:steel_shovel>,
    <item:galacticraftplanets:desh_spade>,
    <item:galacticraftplanets:titanium_shovel>,
    <item:avaritia:infinity_shovel>,
    //dust
    <item:enderio:item_material:24>,
    <item:enderio:item_material:25>,
    <item:enderio:item_material:26>,
    <item:enderio:item_material:27>,
    <item:enderio:item_material:31>,
    <item:enderio:item_material:30>,
    //gear
    <item:enderio:item_material:9>,
    <item:enderio:item_material:10>,
    <item:enderio:item_material:11>,
    <item:enderio:item_material:12>,
    <item:enderio:item_material:13>,
    <item:enderio:item_material:73>,
    //misc
    <item:tconstruct:clay_cast>,
    <item:itemfilters:filter>,
    <item:forestry:greenhouse>,
    <item:forestry:greenhouse:3>,
    <item:forestry:greenhouse:4>,
    <item:forestry:greenhouse:5>,
    <item:forestry:climatiser>,
    <item:forestry:climatiser:1>,
    <item:forestry:climatiser:2>,
    <item:forestry:climatiser:3>,
    <item:forestry:climatiser:4>,
    itemUtils.getItem("forestry:greenhouse.window"),
    itemUtils.getItem("forestry:greenhouse.window_up"),
    <item:integrateddynamics:squeezer>,
    <item:integrateddynamics:drying_basin>,
    <item:integrateddynamics:mechanical_squeezer>,
    <item:sakura:materials:53>,
    <item:scp:recipe_viewer>,
    <item:scp:ceiling_lamp>,
    <item:scp:lamp>,
    <item:scp:small_lamp>,
    <item:scp:sturdy_chestplate>,
    <item:scp:sturdy_leggings>,
    <item:scp:sturdy_boots>,
    <item:scp:sturdy_helmet>,
    <item:forestry:engine_clockwork>,
    <item:forestry:engine_peat>,
    <item:forestry:engine_biogas>,
    <item:sakura:barrel_out>,
    <item:integrateddynamics:coal_generator>,
    <item:teastory:matcha_cookie>,
    <item:teastory:porkchop_rice>,
    <item:teastory:steak_rice>,
    <item:teastory:chicken_rice>,
    <item:teastory:potato_rice>,
    <item:teastory:rabbit_rice>,
    <item:creepypastacraft:computer>,
    <item:creepypastacraft:computeradvancementslogo>,
    <item:creepypastacraft:creepypastacraftlogo>,
    <item:creepypastacraft:pasta>,
    <item:creepypastacraft:thescare_portal>,
    <item:modularmachinery:itemmodularium>,
    <item:enderio:block_decoration2:10>,
    <item:enderio:block_decoration3:2>,
    <item:enderio:block_combustion_generator>,
    <item:enderio:block_enhanced_combustion_generator>,
    <item:enderio:block_simple_stirling_generator>,
    <item:enderio:block_stirling_generator>,
    <item:enderio:block_zombie_generator>,
    <item:enderio:block_franken_zombie_generator>,
    <item:enderio:block_ender_generator>,
    <item:galacticraftcore:machine>,
    <item:galacticraftcore:aluminum_wire>,
    <item:galacticraftcore:aluminum_wire:1>,
    <item:galacticraftcore:aluminum_wire:2>,
    <item:galacticraftcore:aluminum_wire:3>,
    <item:galacticraftplanets:walkway:1>,
    <item:galacticraftcore:machine:12>,
    <item:galacticraftcore:machine2>,
    <item:fluidtank:blocktank3:3>,
    <item:enderio:item_dark_steel_crook>,
    <item:enderio:item_dark_steel_crook>.withTag({"enderio.darksteel.upgrade.hoe": {level: 0}, "enderio.darksteel.upgrade.direct": {level: 0}, "enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}}),
    <item:enderio:item_dark_steel_hand>,
    <item:enderio:item_dark_steel_hand>.withTag({"enderio.darksteel.upgrade.energyUpgrade": {level: 3, energy: 1000000}}),
    <item:scp:screwdriver>,
    <item:galacticraftcore:machine_tiered:4>,
    <item:galacticraftcore:machine4>,
    <item:forestry:still>,
    <item:forge:bucketfilled>.withTag({FluidName: "fire_water", Amount: 1000}),
    <item:forestry:can:1>.withTag({Fluid: {FluidName: "fire_water", Amount: 1000}}),
    <item:forestry:refractory:1>.withTag({Fluid: {FluidName: "fire_water", Amount: 1000}}),
    <item:forge:bucketfilled>.withTag({FluidName: "hootch", Amount: 1000}),
    <item:forestry:can:1>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
    <item:forestry:capsule:1>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
    <item:forestry:refractory:1>.withTag({Fluid: {FluidName: "hootch", Amount: 1000}}),
    <item:forge:bucketfilled>.withTag({FluidName: "rocket_fuel", Amount: 1000}),
    <item:forestry:can:1>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
    <item:forestry:capsule:1>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
    <item:forestry:refractory:1>.withTag({Fluid: {FluidName: "rocket_fuel", Amount: 1000}}),
    <item:forestry:can:1>.withTag({Fluid: {FluidName: "fuelgc", Amount: 1000}}),
    <item:forestry:capsule:1>.withTag({Fluid: {FluidName: "fuelgc", Amount: 1000}}),
    <item:forestry:refractory:1>.withTag({Fluid: {FluidName: "fuelgc", Amount: 1000}}),
    <item:enderio:block_vat>,
    <item:enderio:block_enhanced_vat>,
    <item:abyssalcraft:odb>,
    <item:enderio:block_simple_wired_charger>,
    <item:enderio:block_wireless_charger>,
    <item:enderio:block_decoration2:15>,
    <item:scp:arrow_proof_vest>,
    <item:avaritia:neutron_collector>,
    <item:abyssalcraft:ingotblock:3>,
    <item:abyssalcraft:crystalcluster:10>,
    <item:abyssalcraft:crystal:10>,
    <item:abyssalcraft:crystalshard:10>,
    <item:abyssalcraft:crystalfragment:10>,
    <item:abyssalcraft:methane>,
    <item:scp:blast_glass>,
    <item:galacticraftcore:steel_pole>,
    <item:galacticraftcore:machine_tiered:12>,
    <item:scp:flashlight>.withTag({On: 0 as byte}),
    <item:scp:battery>,
    <item:scp:unusual_battery>,
    <item:galacticraftcore:canister>,
    <item:avaritia:extreme_crafting_table>,
    <item:avaritia:neutronium_compressor>,
    <item:avaritia:singularity>,
    <item:avaritia:singularity:1>,
    <item:avaritia:singularity:2>,
    <item:avaritia:singularity:3>,
    <item:avaritia:singularity:4>,
    <item:avaritia:singularity:5>,
    <item:avaritia:singularity:6>,
    <item:avaritia:singularity:7>,
    <item:avaritia:singularity:8>,
    <item:avaritia:singularity:9>,
    <item:avaritia:singularity:10>,
    <item:avaritia:singularity:11>,
    <item:avaritia:singularity:12>,
    <item:avaritia:singularity:13>,
    <item:avaritia:singularity:14>,
    <item:extendedcrafting:material>,
    <item:extendedcrafting:storage>,
    <item:extendedcrafting:trimmed>,
    <item:extendedcrafting:trimmed:1>,
    <item:extendedcrafting:trimmed:2>,
    <item:extendedcrafting:trimmed:3>,
    <item:extendedcrafting:trimmed:4>,
    <item:extendedcrafting:trimmed:5>,
    <item:extendedcrafting:material:3>,
    <item:extendedcrafting:material:1>,
    <item:extendedcrafting:material:2>,
    <item:extendedcrafting:table_basic>,
    <item:extendedcrafting:material:9>,
    <item:extendedcrafting:material:10>,
    <item:extendedcrafting:material:12>,
    <item:extendedcrafting:material:14>,
    <item:extendedcrafting:material:15>,
    <item:extendedcrafting:material:16>,
    <item:extendedcrafting:material:17>,
    <item:extendedcrafting:material:18>,
    <item:extendedcrafting:storage:5>,
    <item:extendedcrafting:material:36>,
    <item:extendedcrafting:material:37>,
    <item:extendedcrafting:guide>,
    <item:forestry:portable_alyzer>,
    <item:forestry:bee_house>,
    <item:forestry:rainmaker>,
    <item:extendedcrafting:frame>,
    <item:extendedcrafting:lamp>,
    <item:extendedcrafting:lamp:1>,
    <item:torcherino:timewand>,
    <item:torcherino:diamondclock>,
    <item:torcherino:emeraldclock>,
    <item:torcherino:lapisclock>,
    <item:torcherino:redstoneclock>,
    <item:torcherino:goldclock>,
    <item:torcherino:bindingelement>,
    <item:torcherino:bindingelement2>,
    <item:enderio:item_material:55>,
    <item:galacticraftplanets:geothermal_generator>,
    <item:extendedcrafting:storage:3>,
    <item:galacticraftcore:canister:1>,
    <item:refinedstorage:quartz_enriched_iron_block>,
    <item:teslacorelib:base_addon>,
    <item:refinedstorage:machine_casing>,
    <item:galacticraftplanets:solar_array_controller>,
    <item:galacticraftplanets:solar_array_module>,
    <item:tconevo:metal:18>,
    <item:tconevo:metal:33>,
    <item:tconevo:metal:28>,
    <item:galacticraftplanets:laser_turret>,
    <item:compactmachines3:wallbreakable>,
    <item:compactmachines3:machine>,
    <item:compactmachines3:machine:1>,
    <item:compactmachines3:machine:2>,
    <item:compactmachines3:machine:3>,
    <item:compactmachines3:machine:4>,
    <item:compactmachines3:machine:5>,
    <item:compactmachines3:psd>,
    <item:compactmachines3:tunneltool>,
    <item:compactmachines3:redstonetunneltool>,
    <item:requious:tuning_fork>,
    <item:requious:shape>,
    // <item:hbm:anvil_iron>,
    // <item:hbm:anvil_lead>,
    // <item:hbm:anvil_steel>,
    // <item:hbm:anvil_meteorite>,
    // <item:hbm:anvil_starmetal>,
    // <item:hbm:anvil_ferrouranium>,
    // <item:hbm:anvil_bismuth>,
    // <item:hbm:anvil_schrabidate>,
    // <item:hbm:anvil_dnt>,
    // <item:hbm:anvil_osmiridium>,
    // <item:hbm:anvil_murky>,
    // <item:hbm:stamp_stone_flat>,
    // <item:hbm:stamp_stone_plate>,
    // <item:hbm:stamp_stone_wire>,
    // <item:hbm:stamp_stone_circuit>,
    // <item:hbm:stamp_iron_flat>,
    // <item:hbm:stamp_iron_plate>,
    // <item:hbm:stamp_iron_wire>,
    // <item:hbm:stamp_iron_circuit>,
    // <item:hbm:stamp_obsidian_flat>,
    // <item:hbm:stamp_obsidian_plate>,
    // <item:hbm:stamp_obsidian_wire>,
    // <item:hbm:stamp_obsidian_circuit>,
    <item:galacticraftcore:fluid_tank>,
    <item:galacticraftplanets:walkway:2>,
    <item:galacticraftcore:fluid_pipe>,
    // <item:hbm:template_folder>,
    // <item:hbm:machine_press>,
    // <item:hbm:machine_epress>,
    <item:tconstruct:cast_custom:3>,
    itemUtils.getItem("baublelicious:item.itemmagiccore"),
    itemUtils.getItem("baublelicious:item.itemmagiccore", 1),
    itemUtils.getItem("baublelicious:item.itemmagiccore", 2),
    <item:galacticraftcore:food:9>,
    <item:galacticraftcore:food:3>,
    <item:galacticraftcore:food:2>,
    <item:galacticraftcore:food:1>,
    <item:galacticraftcore:food>,
    <item:galacticraftcore:basic_item:18>,
    <item:galacticraftcore:basic_item:17>,
    <item:galacticraftcore:basic_item:16>,
    <item:galacticraftcore:basic_item:15>,
    <item:bloodmagic:mimic>,
    <item:bloodmagic:mimic:1>,
    <item:bloodmagic:mimic:2>,
    <item:bloodmagic:mimic:3>,
    <item:bloodmagic:mimic:4>,
    // <item:hbm:machine_difurnace_off>,
    // <item:hbm:machine_difurnace_rtg_off>,
    <item:bloodmagic:soul_snare>,
    <item:bloodmagic:sentient_sword>.withTag({}),
    <item:bloodmagic:sentient_axe>.withTag({}),
    <item:bloodmagic:sentient_pickaxe>.withTag({}),
    <item:bloodmagic:sentient_shovel>.withTag({}),
    // <item:hbm:machine_boiler_off>,
    // <item:hbm:machine_boiler_electric_off>,
    // <item:hbm:machine_boiler_rtg_off>,
    // <item:hbm:machine_boiler_on>,
    // <item:hbm:machine_boiler_electric_on>,
    // <item:hbm:machine_boiler_rtg_on>,
    // <item:hbm:machine_solar_boiler>,
    // <item:hbm:book_guide_book:2>,
    // <item:hbm:ingot_meteorite_forged>,
    // <item:hbm:blade_meteorite>,
    <item:ifgretro:rubber_bar>,
    <item:ifgretro:raw_plastic>,
    // <item:hbm:cobalt_pickaxe>,
    <item:mctsmelteryio:machine>,
    <item:sakura:tea:8>,
    <item:sakura:tea:7>,
    <item:sakura:tea:6>,
    <item:sakura:tea:10>,
    <item:sakura:tea:2>,
    <item:sakura:tea:11>,
    <item:sakura:tea:3>,
    <item:sakura:tea>,
    <item:sakura:tea:5>,
    <item:sakura:tea:4>,
    <item:sakura:tea:9>,
    <item:sakura:tea:1>,
    <item:sakura:tea:12>,
    <item:sakura:materials>,
    <item:sakura:rice_seeds>,
    <item:teastory:washed_rice>,
    <item:teastory:xian_rice>,
    <item:teastory:rice_ball>,
    <item:enderio:item_material:21>,
    // <item:hbm:bobmazon_weapons>,
    <item:mcjtylib_ng:multipart>,
    <item:mctsmelteryio:upgrade>,
    /*
    Those are already disabled in Industrial Foregoing config
    
    <item:industrialforegoing:black_hole_unit>,
    <item:industrialforegoing:black_hole_controller>,
    <item:industrialforegoing:black_hole_controller_reworked>,
    <item:industrialforegoing:black_hole_tank>,
    <item:industrialforegoing:oredictionary_converter>,
    <item:industrialforegoing:pitiful_fuel_generator>,
    <item:industrialforegoing:fluid_crafter>
    */
    <item:tconevo:metal_block>,
    <item:tconevo:metal_block:1>,
    <item:tconevo:metal_block:2>,
    <item:tconevo:metal_block:4>,
    <item:tconevo:metal_block:7>,
    <item:tconevo:metal_block:8>,
    ] as IItemStack[];

var banned_item_tooltip as string = game.localize("banned_item_tooltip");
var banned_item_compensation_tooltip as string = game.localize("banned_item_compensation_tooltip");
static banned_item_index as int = 0;

for item in banned_items
{
    if (!isNull(item))
    {
        recipes.remove(item);
        JEI.hide(item);
        if (!item.hasTag)
        {
            item.clearTooltip(true);
            item.displayName = banned_item_tooltip;
            item.addTooltip(banned_item_compensation_tooltip);
            recipes.addHiddenShapeless("banned_item_compensation_" + banned_item_index, <item:sakura:foodset:131>, [item]);
            banned_item_index += 1;
        }
    }
}

events.onPlayerPickupItem(function(event as PlayerPickupItemEvent)
{
    if (event.player.world.remote) return;
    if (event.item.item.definition.id == "sakura:rice_seeds")
    {
        event.item.onKillCommand();
        event.cancel();
        event.player.give(<item:teastory:xian_rice_seeds>);
    }
});

var banned_fluids = [
    <liquid:fire_water>,
    <liquid:hootch>,
    <liquid:rocket_fuel>
    ] as ILiquidStack[];

for fluid in banned_fluids
{
    JEI.hide(fluid);
}

var banned_categories = [
    "integrateddynamicscompat:squeezer",
    "integrateddynamicscompat:dryingBasin",
    "integrateddynamicscompat:mechanicalSqueezer",
    "ZombieGenerator",
    "EnderGenerator",
    "StirlingGenerator",
    "CombustionGenerator",
    "forestry.still",
    "Vat",
    "jeresources.enchantment",
    "jeresources.worldgen",
    "galacticraft.ingotcompressor",
    // "hbm.anvil",
    // "hbm.press",
    // "hbm.alloy",
    "ftbquests.quests",
    "Painter",
    "teastory.cookingpan",
    "minecraft.anvil"
    ] as string[];

for category in banned_categories
{
    JEI.hideCategory(category);
}
